[package]
name = "edgedns"
version = "0.1.0"
authors = ["Frank Denis <github@pureftpd.org>"]

[features]
webservice = ["civet", "conduit", "conduit-middleware", "conduit-router"]

[dependencies]
env_logger = "*"
log = "*"
rand = "*"
rustc-serialize = "*"
slab = "*"

[dependencies.civet]
version = "*"
optional = true

[dependencies.conduit]
version = "*"
optional = true

[dependencies.conduit-middleware]
version = "*"
optional = true

[dependencies.conduit-router]
version = "*"
optional = true

[dependencies.cart-cache]
git = "https://github.com/jedisct1/rust-cart"

[dependencies.bytes]
git = "https://github.com/carllerche/bytes"

[dependencies.clap]
git = "https://github.com/kbknapp/clap-rs.git"

[dependencies.mio]
git = "https://github.com/carllerche/mio"

[dependencies.nix]
git = "https://github.com/carllerche/nix-rust.git"

[profile.dev]
codegen-units = 4
panic = "unwind"

[profile.release]
debug = true
lto = true
panic = "abort"
